name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

    - name: Copy files to EC2
      run: scp -r -o StrictHostKeyChecking=no ./* ec2-user@3.89.222.44:/home/ec2-user/deadpods2

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.89.222.44 << 'EOF'
          cd /home/ec2-user/deadpods2
          # Example commands to restart services, install dependencies, etc.
          npm install
          pm2 restart all
        EOF
